### ISSUE TITLE
Info: Chats does not work with actual mesa-20.3.0 : do not update

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#58] opened 2020-12-02 15:52 UTC
**Problem:**

Dez 01 23:53:04 fedorapine systemd-coredump[4945]: [🡕] Process 4915 (chatty) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 4915:
                                                   #0  0x0000000000000000 n/a (n/a + 0x0)
                                                   #1  0x0000007f5efb4214 gst_vulkan_physical_device_fill_info.constprop.0 (libgstvulkan-1.0.so.0 + 0x27214)
                                                   #2  0x0000007ffaa4dfe0 n/a (n/a + 0x0)

================================================================================
     FEDORA-2020-8288e766d9
================================================================================
    Release: Fedora 34
     Status: stable
       Type: unspecified
   Severity: unspecified
      Karma: -1
      Notes: Automatic update for mesa-20.3.0~rc3-2.fc34.
  Submitter: pbrobinson

**Workaround if you hit this problem:**

$ dnf downgrade https://kojipkgs.fedoraproject.org//packages/mesa/20.2.3/2.fc34/aarch64/mesa-vulkan-drivers-20.2.3-2.fc34.aarch64.rpm

$ sudo echo "exclude=mesa*"  >>/etc/dnf/dnf.conf

**Comment by nikhiljha** [comment] 2020-12-02 18:20
rehosting the package here since that link will die soon

[mesa-vulkan-drivers-20.2.3-2.fc34.aarch64.zip](https://github.com/nikhiljha/pp-fedora-sdsetup/files/5631292/mesa-vulkan-drivers-20.2.3-2.fc34.aarch64.zip)

**Comment by Torbuntu** [comment] 2021-01-17 15:41
Best I can tell the issue is fixed with `mesa-vulkan-drivers-20.3.3-3.fc33.aarch64`

**Closed** 2021-01-18 00:31 UTC
